### PR TITLE
Add to defaults parmas all Operator and Sensor params, not only args

### PR DESCRIPTION
**Pull request by tsvetkov-ii**
Defaults section only works for args, but not only args may be defaults. 

This PR adds support for defaults class, callback_args, callback.

### CODE REVIEW

**Comment by kxepal** [comment]
@tsvetkov-ii Could you please fix a typo in commit message?

**Comment by KostyaEsmukov** [comment]
> @tsvetkov-ii Could you please fix a typo in commit message?

@kxepal BTW, you can change it yourself by choosing "Squash and Merge"  when merging.

**Comment by tsvetkov-ii** [comment]
> @tsvetkov-ii Could you please fix a typo in commit message?

DId it

**Comment by kxepal** [comment]
Thanks!

**Pull request merged**
